=== jasonf-vim/XQ-RPC/framework/core/src/main/java/org/jasonf/builder/xml/XQ-config.dtd
<?xml version="1.0" encoding="UTF-8" ?>
        <!ELEMENT configuration ANY>

        <!ELEMENT app ANY>

        <!ELEMENT group ANY>

        <!ELEMENT port ANY>

        <!ELEMENT registry EMPTY>
        <!ATTLIST registry
                url CDATA #REQUIRED
                >

        <!ELEMENT serialize EMPTY>
        <!ATTLIST serialize
                type CDATA #REQUIRED
                >

        <!ELEMENT compress EMPTY>
        <!ATTLIST compress
                type CDATA #REQUIRED
                >

        <!ELEMENT id-generator EMPTY>
        <!ATTLIST id-generator
                class CDATA #REQUIRED
                room CDATA #REQUIRED
                server CDATA #REQUIRED
                >

        <!ELEMENT load-balancer EMPTY>
        <!ATTLIST load-balancer
                class CDATA #REQUIRED
                >

=== jasonf-vim/XQ-RPC/demo/invoker/src/main/resources/XQ-config.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE configuration SYSTEM "http://jasonf.org/XQ-config.dtd">
<configuration>
    <!-- 应用名 -->
    <app>XQ-Invoker</app>

    <!-- 分组 -->
    <group>master</group>

    <!-- 注册中心 -->
    <registry url="zookeeper://123.60.86.242:2181"/>

    <!-- 序列化器 -->
    <serialize type="jdk"/>

    <!-- 报文压缩方式 -->
    <compress type="gzip"/>

    <!-- ID生成器 -->
    <id-generator class="org.jasonf.generator.impl.SnowIDGenerator" room="3" server="5"/>

    <!-- 负载均衡器 -->
    <load-balancer class="org.jasonf.loadbalance.impl.MinResponseTimeLoadBalancer"/>

</configuration>
